name: GeorgiaFailsAtCoding
version: 2.0
author: GeorgiaMarie98x
main: georgiafailsatcoding.georgiafailsatcoding.GeorgiaFailsAtCoding
api-version: 1.19
description: Georgia WINS at plugin development! :D